framework:
  name: "Campaign Data Quality Framework"
  catalog: "wmg"

  excluded_schemas:
    - information_schema

  default_status_thresholds:
    pass: 90
    warning: 75
    fail: 0


dq_rules:

  completeness:
    id: DQ01
    enabled: true
    weight: 10
    level: column
    severity: high

    rules:
      required_columns:
        enabled: true
        columns:
          - customer_id
          - email


  accuracy:
    id: DQ02
    enabled: true
    weight: 10
    level: row
    severity: high

    rules:
      numeric_values:
        enabled: true
        reject_nan: true


  validity:
    id: DQ03
    enabled: true
    weight: 8
    level: column
    severity: high

    rules:
      allowed_values: {}


  uniqueness:
    id: DQ04
    enabled: true
    weight: 8
    level: dataset
    severity: critical

    rules:
      unique_keys:
        wmg.default.customers_100:
          - customer_id

        wmg.demo.transactions:
          - transaction_id


  consistency:
    id: DQ05
    enabled: true
    weight: 7
    level: row
    severity: medium

    rules:
      rules: []


  integrity:
    id: DQ06
    enabled: true
    weight: 7
    level: cross_table
    severity: critical

    rules:
      relationships: []


  timeliness:
    id: DQ07
    enabled: true
    weight: 6
    level: dataset
    severity: high

    rules:
      freshness_hours: 24


  conformity:
    id: DQ08
    enabled: true
    weight: 5
    level: column
    severity: medium

    rules:
      standards: {}


  range:
    id: DQ09
    enabled: true
    weight: 5
    level: row
    severity: high

    rules:
      ranges: {}


  duplicate:
    id: DQ10
    enabled: true
    weight: 7
    level: dataset
    severity: high

    rules:
      duplicate_keys: {}


  "null":
    id: DQ11
    enabled: true
    weight: 8
    level: column
    severity: high

    rules:
      max_null_percentage: 5


  length:
    id: DQ12
    enabled: true
    weight: 4
    level: column
    severity: medium

    rules:
      max_length: {}


  data_type:
    id: DQ13
    enabled: true
    weight: 5
    level: column
    severity: high

    rules:
      expected_types: {}


  pattern:
    id: DQ14
    enabled: true
    weight: 4
    level: column
    severity: medium

    rules:
      regex_patterns: {}


  business_rule:
    id: DQ15
    enabled: true
    weight: 5
    level: row
    severity: critical

    rules:
      expressions: {}


  volume:
    id: DQ16
    enabled: true
    weight: 1
    level: dataset
    severity: medium

    rules:
      expected_min: {}
      expected_max: {}
      variance_percentage: 15